### ISSUE TITLE
1.2 CE can't be played without Expansion Pak

### ISSUE THREAD

**Issue by Xalusc** [jordanbarkley/19XX#12]
I thought I would be able to play v1.2 CE without an Expansion Pak, since an earlier version states on its release notes that it was possible, but it just doesn't boot up.
Works fine with an Expansion Pak, though. 

Using an ED64 Plus, newest version. NTSC-U console and ROM.

**Comment by jordanbarkley** [comment]
This isn't a bug but I've added a note in README.md. Closed
