### ISSUE TITLE
19XXCE 1.4 Combo Meter crash

### ISSUE THREAD

**Issue by luigidoed** [jordanbarkley/19XX#16]
19XXCE 1.4
Emulator

If you do something like Down air to cargo grab on any character it'll freeze the game if improved combo meter is on.
Issue on emulator not sure if reproducible on console
Turning Improved combo meter off fixes this bug also (so grabs don't count as combo) Didn't record footage of that though as I originally thought the bug was in the combo meter itself
https://www.youtube.com/watch?v=bEF6_8H-gto

**Comment by jtl3d** [comment]
Have you confirmed if this was not an issue in pre-vs mode combo meter versions? And it is the improved combo meter toggle that matters, not the vs mode combo meter toggle?

**Comment by luigidoed** [comment]
Improved combo meter seems to be the toggle that matters for 19XXCE 1.4. I haven't been able to reproduce the issue with it off. The vs combo meter toggle seems fine on it's own.

On another note on 19XXCE 1.3 I can't reproduce the same error with all combo meter toggles on. 

https://www.youtube.com/watch?v=M_Xr9RGUeKo A video showing both of those off

**Comment by jtl3d** [comment]
Finally merged in this fix.
