### ISSUE TITLE
19XXTE 1.4 Exit Menu Crash?

### ISSUE THREAD

**Issue by Jammster** [jordanbarkley/19XX#18]
19XXTE 1.4
Emulator (Wii64 1.2 Beta (Mupen64))

Attempting to exit out of the main menu in 19XXTE will freeze the game, requiring to reset. This only happens in 19XXTE, not in 19XXCE. Not sure if it's an emulator problem or not.

**Comment by buvk** [comment]
Freeze occurs on console as well.

**Comment by jtl3d** [comment]
Thanks! Should be fixed now. I'll make a release soon.
