### ISSUE TITLE
Floating Point Exception (Part 2)

### ISSUE THREAD

**Issue by GB-CG** [jordanbarkley/19XX#6]
Mod: 19XXCE
Version: 1.1 Beta
Console or emulator: Console
Level: Dream Land Beta 2
Mode: Vs., Free-for-all
Players: 1 vs 3 CPU's
Items: All on, very high

It crashed about a minute or 2 in the match. Items seem to have appeared less then usual. Probably related to #5.

Edit: Seems like the items are the culprit, regardless of their rate and selection. Without them, it doesn't crash.

<details><summary>Pic 1</summary>
<img src="https://user-images.githubusercontent.com/11931125/50702321-81083800-1048-11e9-9104-bead3ef9602e.png"</img></details>

<details><summary>Pic 2</summary> 
<img src="https://user-images.githubusercontent.com/11931125/50702357-9da47000-1048-11e9-9f06-54f36b1e884b.png"</img></details>

<details><summary>Pic 3</summary> 
<img src="https://user-images.githubusercontent.com/11931125/50702394-bdd42f00-1048-11e9-9b50-6db9d1f5d8e7.png"</img></details>

**Comment by jordanbarkley** [comment]
Thanks for your detailed reply. I’ll hook into the item spawn function and add new points to fix the stage until the stage editor is complete.

**Comment by GB-CG** [comment]
I'll close this for now.
