### ISSUE TITLE
Attempting to access options causes game to freeze when using project 64

### ISSUE THREAD

**Issue by littlelum** [jordanbarkley/19XX#9]
When I try to access one of the options menus, (like 19xx menu or random stage menu) the game freezes and refuses to take any input.

**Comment by jordanbarkley** [comment]
This is not a 19XX bug. This is likely a plugin issue. I'd suggest [GLideN64](https://gliden64.blogspot.com/2019/04/public-release-40.html).

**Comment by jtl3d** [comment]
If this is old pj64 (pj64kve) than it is fixed in #14.
